### ISSUE TITLE
FR - Setting to display each language display name in that language 

### ISSUE THREAD

**Issue by tigerchick** [spacemonkxyz/craft-language-manager#1]
When using {% hook 'languageManagerNavigation' %} it would be useful to display each language display name actually in that language.
So, for example if I'm currently on the Japanese site, the language list would be displayed like this:

English
Português
日本語

Instead of the current:
英語
ポルトガル語
日本語

**Comment by tigerchick** [comment]
Just realised that this can actually be achived using the custom translations setting and then providing effectively the same file in each language folder without deviating the translations. eg:
```
<?php

return [
	'en-GB' => 'English',
	'pt' => 'Português',
	'fr-FR' => 'Français',
	'es-ES' => 'Español',
	'es-ES' => 'Español',
	'de-DE' => 'Deutsch',
	'it-IT' => 'Italiano',
	'ja-JP' => '日本語'
];
```

**Comment by worzst** [comment]
@tigerchick Thanks for your feedback. I hope your solution works fine for you.

I'll have a look to add this as an option to the settings.

(and sorry for the late reply, notification didn't come through)

**Comment by worzst** [comment]
@tigerchick thanks again for the great suggestion, it is now part of the new version 1.1.0 and is available on the plugin store.

I extended the settings menu with a simple button to make this usable for all users.

![Screenshot 2024-04-06 at 12 15 57 AM](https://github.com/spacemonkxyz/craft-language-manager/assets/10532854/079efa06-3cd2-43e5-957a-98bde910894e)

**Comment by tigerchick** [comment]
Awesome! Great job - thanks for implementing :)
